Revert "Bump selenium-webdriver from 4.19.0 to 4.20.0 (#3)"
This reverts commit 038b94d8283cb204cd711c1292f55af98a38e708.

Fixes the following error when running a system test:

```
undefined method `path' for class Selenium::WebDriver::DriverFinder (NoMethodError)
namespace::Service.driver_path = ::Selenium::WebDriver::DriverFinder.path(options, namespace::Service)
```